name: huawei_push_example
description: Demonstrates how to use the Huawei Push plugin.
version: 5.0.2+302

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  huawei_push:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
